CREATE TABLE users
(
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
--     email VARCHAR(255) NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     password_salt VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);